Add Scala to statically typed languages
reactjs/react.dev pull request #4210
Opened 2022-01-05 18:12 UTC by mgibowski

2022-01-11 20:01 UTC, import-brain requested changes

2022-01-11 20:01 UTC, import-brain commented on content/docs/static-type-checking.md
> +[Scala](https://scala-lang.org/) is a statically typed language developed by Swiss Federal Institute of Technology in Lausanne. Its target platforms include JVM and [JavaScript](https://www.scala-js.
```suggestion
[Scala](https://scala-lang.org/) is a statically typed language developed by the Swiss Federal Institute of Technology in Lausanne. Its target platforms include JVM and [JavaScript](https://www.scala-js.org/).
```
minor grammatical change

2022-01-12 17:37 UTC, import-brain approved these changes
LGTM!

2024-08-21 12:02 UTC, BartoszKlonowski commented
Hello @mgibowski!
As static type checkers have no section in the react.dev docs now, I will close this PR as outdated.
Thank you!

2024-08-21 12:02 UTC, closed without merging