Update and fix gh actions
reactjs/react.dev pull request #6651
Opened 2024-02-20 21:57 UTC by alinkedd

2024-04-16 21:43 UTC, alinkedd commented
@gaearon @harish-sethuraman could you please help to find someone to review this PR regarding GH actions? It would be great to have them fixed.

duplicates https://github.com/reactjs/react.dev/pull/6179#issuecomment-1955047477
fyi @rickhanlonii

2024-11-04 22:52 UTC, alinkedd commented
@poteto hi
I noticed you've worked with GitHub Actions. Could you please take a look at this PR as well?

2024-11-05 19:34 UTC, poteto requested changes
thanks for the contribution! rather than update the existing external action, i would rather we make use of the github ones. could you help rewrite them to use it instead?

2024-11-05 19:34 UTC, poteto commented on .github/workflows/analyze.yml
> +        uses: dawidd6/action-download-artifact@v6
do we really need an external action for this? could we rewrite this to use https://github.com/actions/toolkit/tree/main/packages/artifact instead?

2025-03-03 21:22 UTC, alinkedd commented
Close in favor of #7667

2025-03-03 21:22 UTC, closed without merging

2025-03-03 21:37 UTC, alinkedd commented on .github/workflows/analyze.yml
> +        uses: dawidd6/action-download-artifact@v6
@poteto I've completely forgot about this one :) I've moved the fixes to #7667 since they're small and ready to go.

However, I'm not available to work on the improvement of switching from `dawidd6/action-download-artifact` to the latest version of `actions/download-artifact`, perhaps it could be converted into a separate issue