Add info about App.js 2025 conference
reactjs/react.dev pull request #7154
Opened 2024-09-10 08:52 UTC by piaskowyk

This PR adds info about the App.js conference in 2025 🎉

2024-09-30 16:59 UTC, rickhanlonii requested changes

2024-09-30 16:59 UTC, rickhanlonii commented on src/content/community/conferences.md
> +### App.js Conf 2025 {/*appjs-conf-2025*/}
Can you move this down? These are sorted by newest

2024-12-18 09:30 UTC, piaskowyk commented
@rickhanlonii sorry for the ping 🙏 are there any changes to review?

2024-12-18 09:40 UTC, harish-sethuraman approved these changes

2024-12-18 09:40 UTC, merged